version = "1.0"

[main]
name = "WordPress configuration"

    [main.maintenance_mode]
    name = "Maintenance mode"

        [main.maintenance_mode.maintenance_mode]
        ask = "Enable maintenance mode"
        type = "boolean"
        default = "0"

    [main.overwrite_files]
    name = "Overwriting config files"

        [main.overwrite_files.overwrite_nginx]
        ask = "Overwrite the NGINX config file?"
        type = "boolean"
        default = true
        help = "If the file is overwritten, a backup will be created."

        [main.overwrite_files.overwrite_phpfpm]
        ask = "Overwrite the PHP-FPM config file?"
        type = "boolean"
        default = true
        help = "If the file is overwritten, a backup will be created."

    [main.global_config]
    name = "Global configuration"

        [main.global_config.admin_mail_html]
        ask = "Send HTML email to admin?"
        type = "boolean"
        default = true
        help = "Allow app scripts to send HTML mails instead of plain text."

    [main.php_fpm_config]
    name = "PHP-FPM configuration"

        [main.php_fpm_config.fpm_footprint]
        ask = "Memory footprint"
        type = "select"
        choices.low = "Low, <= 20Mb per pool"
        choices.medium = "Medium, between 20Mb and 40Mb per pool"
        choices.high = "High, > 40Mb per pool"
        choices.specific = "Use specific value"
        default = "low"

        [main.php_fpm_config.fpm_free_footprint]
        visible = "fpm_footprint == 'specific'"
        ask = "Memory footprint of the service?"
        type = "number"
        default = "0"
        help = "Free field to specify exactly the footprint in Mb if you don't want to use one of the three previous values."

        [main.php_fpm_config.fpm_usage]
        ask = "Expected usage"
        type = "select"
        choices = ["low", "medium", "high"]
        default = "low"
        help = "low: Personal usage, behind the SSO. No RAM footprint when not used, but the impact on the processor can be high if many users are using the service.<br>medium: Low usage, few people or/and publicly accessible. Low RAM footprint, medium processor footprint when used.<br>high: High usage, frequently visited website. High RAM footprint, but lower on processor usage and quickly responding."
